spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
spring.data.redis.url=${REDIS_URL}
spring.threads.virtual.enabled=true
spring.messages.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
# API Ключ (краще винести в змінну оточення через ${...})
spring.ai.openai.api-key=${OPENAI_API_KEY}
# Вибір моделі (gpt-4o - база для 2026 року)
spring.ai.openai.chat.options.model=gpt-3.5-turbo
# Температура: 0.0 робить відповіді максимально точними і технічними (те що треба для JSON)
# 1.0 - зробить AI креативним "художником", який почне вигадувати поля
spring.ai.openai.chat.options.temperature=0.0
# Рівень логування для твого пакету (зміни com.cr0w на свій, якщо треба)
logging.level.com.cr0w.smartplanner=DEBUG
# Логи Spring AI (побачиш промпти та сирі відповіді від OpenAI)
logging.level.org.springframework.ai=DEBUG
# Загальний рівень для Spring Framework
logging.level.org.springframework.web=DEBUG